version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
      - 3000:3000
      - 30000:30000
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf