version: '3.2'

services:
  nginx:
    container_name: nginx
    image: nginx:1.16-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/conf.d:/etc/nginx/conf.d
      - ./data/log:/var/log/nginx
      - ./data/nginx.conf:/etc/nginx/nginx.conf
